Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/02/2019
Var
// Seção de Declarações das variáveis 
x,litro: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

Escreva ("Quanto você irá pagar? R$:")
leia(x)
x <- x/3,75
escreval ("Você terá ",x:2:2," litros")

Fimalgoritmo