Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/02/2019
Var
// Seção de Declarações das variáveis 
       x: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Ta calor?")
leia(x)
escreval((9 * x + 160) / 5)

Fimalgoritmo