algoritmo "semnome"
// Função :
// Autor :
// Data : 27/02/2019
// Seção de Declarações 
var
i,ganho,despesas:real
ano : inteiro
inicio
escreval("Digite o valor do seu ganho:")
leia(ganho)
escreval("Digite o valor da sua despesa:")
leia(despesas)


enquanto i < 1000000 faca
i <- i + (ganho+despesas)
ano <- ano + 1
fimenquanto
escreval("vai demorar ",ano," anos para você se tornar um milhionário")

fimalgoritmo
